# fly.toml app configuration file generated for practice-viata-buna-rough-log-6878 on 2025-07-31T13:42:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'practice-viata-buna-rough-log-6878'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
